export type Country = {
  name: string
  code: string
  emoji: string
  alternatives?: string[]
}
export const COUNTRIES: Country[] = [
  { name: "Albania", code: "AL", emoji: "🇦🇱" },
  { name: "Andorra", code: "AD", emoji: "🇦🇩" },
  { name: "Austria", code: "AT", emoji: "🇦🇹" },
  { name: "Belarus", code: "BY", emoji: "🇧🇾" },
  { name: "Belgium", code: "BE", emoji: "🇧🇪" },
  { name: "Bosnia and Herzegovina", code: "BA", emoji: "🇧🇦" },
  { name: "Bulgaria", code: "BG", emoji: "🇧🇬" },
  { name: "Croatia", code: "HR", emoji: "🇭🇷" },
  { name: "Cyprus", code: "CY", emoji: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", emoji: "🇨🇿" },
  { name: "Denmark", code: "DK", emoji: "🇩🇰" },
  { name: "Estonia", code: "EE", emoji: "🇪🇪" },
  { name: "Faroe Islands", code: "FO", emoji: "🇫🇴" },
  { name: "Finland", code: "FI", emoji: "🇫🇮" },
  { name: "France", code: "FR", emoji: "🇫🇷" },
  { name: "Germany", code: "DE", emoji: "🇩🇪" },
  { name: "Gibraltar", code: "GI", emoji: "🇬🇮" },
  { name: "Guernsey", code: "GG", emoji: "🇬🇬" },
  { name: "Greece", code: "GR", emoji: "🇬🇷" },
  { name: "Hungary", code: "HU", emoji: "🇭🇺" },
  { name: "Iceland", code: "IS", emoji: "🇮🇸" },
  { name: "Ireland", code: "IE", emoji: "🇮🇪" },
  { name: "Italy", code: "IT", emoji: "🇮🇹" },
  { name: "Jersey", code: "JE", emoji: "🇯🇪" },
  { name: "Latvia", code: "LV", emoji: "🇱🇻" },
  { name: "Liechtenstein", code: "LI", emoji: "🇱🇮" },
  { name: "Lithuania", code: "LT", emoji: "🇱🇹" },
  { name: "Luxembourg", code: "LU", emoji: "🇱🇺" },
  { name: "Malta", code: "MT", emoji: "🇲🇹" },
  { name: "Moldova", code: "MD", emoji: "🇲🇩" },
  { name: "Monaco", code: "MC", emoji: "🇲🇨" },
  { name: "Montenegro", code: "ME", emoji: "🇲🇪" },
  { name: "Netherlands", code: "NL", emoji: "🇳🇱" },
  { name: "North Macedonia", code: "MK", emoji: "🇲🇰" },
  { name: "Norway", code: "NO", emoji: "🇳🇴" },
  { name: "Poland", code: "PL", emoji: "🇵🇱" },
  { name: "Portugal", code: "PT", emoji: "🇵🇹" },
  { name: "Romania", code: "RO", emoji: "🇷🇴" },
  { name: "Russia", code: "RU", emoji: "🇷🇺" },
  { name: "San Marino", code: "SM", emoji: "🇸🇲" },
  { name: "Serbia", code: "RS", emoji: "🇷🇸" },
  { name: "Slovakia", code: "SK", emoji: "🇸🇰" },
  { name: "Slovenia", code: "SI", emoji: "🇸🇮" },
  { name: "Spain", code: "ES", emoji: "🇪🇸" },
  { name: "Sweden", code: "SE", emoji: "🇸🇪" },
  { name: "Switzerland", code: "CH", emoji: "🇨🇭" },
  { name: "Turkey", code: "TR", emoji: "🇹🇷", alternatives: ["Türkiye"] },
  { name: "Ukraine", code: "UA", emoji: "🇺🇦" },
  { name: "United Kingdom", code: "GB", emoji: "🇬🇧" },
  { name: "Vatican City", code: "VA", emoji: "🇻🇦" },
]
