export const languages = [
  { code: "en", name: "English", country: "United Kingdom" },
  { code: "fr", name: "français", country: "France" },
  { code: "es", name: "español", country: "Spain" },
  { code: "nl", name: "Nederlands", country: "Netherlands" },
  { code: "de", name: "Deutsch", country: "Germany" },
  { code: "it", name: "Italiano", country: "Italy" },
  { code: "el", name: "ελληνικά", country: "Greece" },
  { code: "sv", name: "svenska", country: "Sweden" },
  { code: "pt", name: "Português", country: "Portugal" },
  { code: "da", name: "Dansk", country: "Denmark" },
  { code: "no", name: "Norsk", country: "Norway" },
  { code: "pl", name: "polski", country: "Poland" },
  { code: "et", name: "eesti", country: "Estonia" },
  { code: "hr", name: "hrvatski jezik", country: "Croatia" },
  { code: "cy", name: "Cymraeg", country: "Wales" },
  { code: "fi", name: "suomi", country: "Finland" },
  { code: "lt", name: "lietuvių kalba", country: "Lithuania" },
  { code: "ca", name: "Català", country: "Spain" },
  { code: "lb", name: "Lëtzebuergesch", country: "Luxembourg" },
  { code: "bg", name: "български език", country: "Bulgaria" },
  { code: "bs", name: "bosanski jezik", country: "Bosnia and Herzegovina" },
  { code: "hu", name: "magyar", country: "Hungary" },
  { code: "ro", name: "română", country: "Romania" },
  { code: "lv", name: "latviešu valoda", country: "Latvia" },
  { code: "mt", name: "Malti", country: "Malta" },
  { code: "ru", name: "Русский", country: "Russia" },
  { code: "sk", name: "slovenčina", country: "Slovakia" },
  { code: "sl", name: "slovenščina", country: "Slovenia" },
  { code: "sq", name: "Shqip", country: "Albania" },
  { code: "tr", name: "Türkçe", country: "Turkey" },
]
